### ISSUE TITLE
How to specify configuration for gallery repositories?

### ISSUE THREAD

**Issue by rabernat** [pangeo-gallery/pangeo-gallery#1]
Currently the example galleries need a file called `pangeo-gallery.yaml` that looks like this:

```yaml
name: Example Gallery
description: >
  An example gallery of notebooks used for debugging the Pangeo Gallery
  infrastructure.
gallery_repository: pangeo-gallery/pangeo-gallery
binder_url: "http://mybinder.org"
binder_repo: binder-examples/requirements
binder_ref: master
binderbot_target_branch: binderbot-built
```

This information is used by sphinx to generate the index page in https://github.com/pangeo-gallery/pangeo-gallery/blob/master/index.rst.

Does this seem reasonable? What sort of details should we require from the example galleries?

**Comment by jhamman** [comment]
Following up on what we talked about earlier today, I have a few suggestions:

1. rename `pangeo-gallery.yaml` to `binder-gallery.yaml`
1. `binder-gallery.yaml` would go in each example repo, not in the gallery repo. For this reason, you'll likely be able to remove a few keys from your example config (`binderbot_target_branch`, `binder_repo`).
1. The gallery would just keep a master list of repositories and would load the
1. it will likely be useful to list notebooks to be built, e.g.: 
    ```yaml
    ...
    binderbot_target_branch: binderbot-built
    notebooks:
      - path/to/notebook.ipynb
      - path/to/other/notebook.ipynb
    ```
